name: ASP.NET Core CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Install dotnet-script
        run: dotnet tool install dotnet-script --tool-path /usr/bin

      - name: Build
        run: /usr/bin/dotnet-script build/build.csx
