name: ASP.NET Core CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: rojepp/setup-dotnet@fix_dotnet_root
        with:
          dotnet-version: 3.0.100
      - name: Install dotnet-script
        run: dotnet tool install dotnet-script --tool-path dotnet-script-tool

      - name: Build
        run: dotnet-script-tool/dotnet-script build/build.csx
